Repository kubernetes-sigs/release-utils, pull requests merged in 2021-03, with the labels that each got.

#3 log: Do not force colors in global logger configuration
  log/log.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#5 Use Mage for verifies and tests instead of shell scripts and Makefiles
  .gitignore
  .golangci.yml
  dependencies.yaml
  go.mod
  go.sum
  log/log_test.go
  mage.go
  mage/boilerplate.go
  mage/dependency.go
  mage/golang.go
  magefile.go
  scripts/boilerplate/boilerplate.Dockerfile.txt
  scripts/boilerplate/boilerplate.Makefile.txt
  scripts/boilerplate/boilerplate.generatego.txt
  scripts/boilerplate/boilerplate.go.txt
  scripts/boilerplate/boilerplate.py.txt
  scripts/boilerplate/boilerplate.sh.txt
  scripts/verify-build.sh
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XXL

#6 Move env related functionality into own package and apply proper testing
  env/env.go
  env/env_test.go
  env/internal/impl.go
  env/internal/internalfakes/fake_impl.go
  env/internal/internalfakes/fake_impl_iface.go
  go.mod
  go.sum
  internal/tools/tools.go
  util/env_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XL

#4 http.Agent to allow easy URL retrieval
  http/agent.go
  http/http_test.go
  http/httpfakes/fake_agent_implementation.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XL

#8 Move from ioutil to os/io packages
  command/command_test.go
  editor/editor.go
  editor/editor_test.go
  hash/hash_test.go
  http/agent.go
  http/http.go
  http/http_test.go
  log/log_test.go
  tar/tar_test.go
  util/common.go
  util/common_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L
