Repository kubernetes-sigs/release-utils, pull requests merged in 2021-05, with the labels that each got.

#11 Sync PR template from k/release
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, sig/release, size/M

#12 Remove indirect dependencies
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, sig/release, size/XS

#10 Enable dependabot updates
  .github/dependabot.yml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/S

#16 New function hash.SHA1ForFile()
  hash/hash.go
  hash/hash_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, sig/release, size/M

#17 Update golangci-lint to v1.40.1 and fix lints
  .golangci.yml
  dependencies.yaml
  editor/editor.go
  mage/golang.go
  util/common.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M
