Repository kubernetes-sigs/release-utils, pull requests merged in 2022-01, with the labels that each got.

#22 Updates and small bug fix
  dependencies.yaml
  log/log.go
  mage/boilerplate.go
  mage/dependency.go
  mage/golang.go
Labels: kind/bug, approved, size/S, kind/cleanup, cncf-cla: yes, sig/release, lgtm

#24 update repo-infra to v0.2.4
  dependencies.yaml
  mage/boilerplate.go
Labels: approved, kind/cleanup, cncf-cla: yes, sig/release, lgtm, size/XS

#25 sync/update owners
  OWNERS
  OWNERS_ALIASES
Labels: kind/feature, approved, size/S, kind/cleanup, cncf-cla: yes, sig/release, lgtm, kind/documentation

#19 Bump deps
  dependencies.yaml
  env/internal/impl.go
  env/internal/internalfakes/fake_impl.go
  env/internal/internalfakes/fake_impl_iface.go
  go.mod
  go.sum
  http/agent.go
  http/httpfakes/fake_agent_implementation.go
  mage/boilerplate.go
  mage/golang.go
  magefile.go
Labels: approved, area/dependency, size/M, kind/cleanup, cncf-cla: yes, sig/release, lgtm

#26 remove not needed file
  env/internal/internalfakes/fake_impl_iface.go
Labels: approved, size/L, kind/cleanup, cncf-cla: yes, sig/release, lgtm
