Repository kubernetes-sigs/release-utils, pull requests merged in 2022-02, with the labels that each got.

#28 Adding importable version cobra command
  go.mod
  go.sum
  mage/version.go
  mage/version_test.go
  version/command.go
  version/command_test.go
  version/doc.go
  version/verison.go
  version/version_test.go
Labels: kind/feature, approved, size/XXL, cncf-cla: yes, sig/release, lgtm

#29 Add module version support if tool is installed via go install.
  version/verison.go
Labels: kind/feature, approved, size/S, cncf-cla: yes, sig/release, lgtm

#30 Rename verison.go -> version.go
  version/version.go
Labels: approved, kind/cleanup, cncf-cla: yes, sig/release, lgtm, size/XS

#31 Do not attempt to override version if not devel
  version/version.go
Labels: kind/bug, approved, cncf-cla: yes, sig/release, lgtm, size/XS

#33 Add TestGoWithTags Mage target used to run go test with provided tags
  mage/golang.go
Labels: kind/feature, approved, size/S, cncf-cla: yes, sig/release, lgtm

#32 Add mage target for ensuring git config
  mage/git.go
Labels: kind/feature, approved, size/M, cncf-cla: yes, sig/release, lgtm

#35 Minor improvements to CheckGitConfigExists
  mage/git.go
Labels: approved, size/S, kind/cleanup, cncf-cla: yes, sig/release, lgtm
