Repository kubernetes-sigs/release-utils, pull requests merged in 2022-03, with the labels that each got.

#38 Add `ok-to-test` label to dependabot PRs
  .github/dependabot.yml
Labels: approved, cncf-cla: yes, sig/release, lgtm, size/XS

#39 Sync PR template `/kind` with other repos
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, size/S, cncf-cla: yes, sig/release, lgtm, kind/documentation

#42 Switch to golang native error wrapping
  command/command.go
  go.mod
  go.sum
  hash/hash.go
  http/agent.go
  log/log.go
  mage/boilerplate.go
  mage/dependency.go
  mage/git.go
  mage/golang.go
  tar/tar.go
  util/common.go
  util/common_test.go
  version/command.go
Labels: approved, size/L, kind/cleanup, cncf-cla: yes, sig/release, lgtm

#44 add an option to choose an ASCII font
  version/command.go
  version/command_test.go
  version/version.go
Labels: kind/feature, approved, size/S, cncf-cla: yes, sig/release, lgtm

#45 add WithFont function
  version/command.go
  version/command_test.go
Labels: kind/feature, approved, size/S, kind/cleanup, cncf-cla: yes, sig/release, lgtm
