Repository kubernetes-sigs/release-utils, pull requests merged in 2023-05, with the labels that each got.

#78 go.mod: Use uwu-tools/magex
  go.mod
  go.sum
  mage/boilerplate.go
  mage/cosign.go
  mage/dependency.go
  mage/golang.go
  mage/ko.go
  mage/version.go
Labels: approved, area/dependency, size/M, kind/cleanup, cncf-cla: yes, sig/release, lgtm

#81 Fix typos in comments
  command/command_test.go
  http/agent.go
  util/common.go
Labels: approved, cncf-cla: yes, sig/release, lgtm, kind/documentation, size/XS

#83 Add CompressWithoutPreservingPath to tar package
  tar/tar.go
  tar/tar_test.go
Labels: kind/feature, approved, size/M, cncf-cla: yes, sig/release, lgtm

#84 tar/extract: ignore error if directory exists
  tar/tar.go
Labels: kind/bug, approved, cncf-cla: yes, sig/release, lgtm, size/XS
