Repository kubernetes-sigs/release-utils, pull requests merged in 2024-07, with the labels that each got.

#106 Update golangci-lint and fix lints
  .golangci.yml
  command/command.go
  command/command_test.go
  command/global.go
  dependencies.yaml
  editor/editor.go
  hash/hash.go
  hash/hash_test.go
  http/agent.go
  http/http.go
  http/http_test.go
  log/hooks.go
  log/log_test.go
  log/step.go
  mage/boilerplate.go
  mage/cosign.go
  mage/dependency.go
  mage/golangci-lint.go
  mage/ko.go
  mage/version.go
  tar/tar_test.go
  util/common.go
  util/common_test.go
  version/command.go
  version/version.go
  version/version_test.go
Labels: approved, size/L, kind/cleanup, cncf-cla: yes, sig/release, lgtm

#108 Add new throttler pkg forked from nozzle/throttler
  throttler/README.md
  throttler/example_test.go
  throttler/throttler.go
  throttler/throttler_test.go
Labels: kind/feature, approved, size/XL, cncf-cla: yes, sig/release, lgtm

#109 Add util.IsDir method and tests
  util/common.go
  util/common_test.go
Labels: kind/feature, approved, size/M, cncf-cla: yes, sig/release, lgtm

#107 http.Agent: Add `Group` variants for parallel fetching
  http/agent.go
  http/doc.go
  http/example_multi_test.go
  http/http.go
  http/http_test.go
Labels: kind/feature, approved, size/XL, cncf-cla: yes, sig/release, lgtm, kind/documentation

#111 Revert fork of nozzle/throttle
  go.mod
  go.sum
  http/agent.go
  throttler/README.md
  throttler/example_test.go
  throttler/throttler.go
  throttler/throttler_test.go
Labels: approved, kind/cleanup, size/XL, cncf-cla: yes, sig/release, lgtm

#110 Add release workflow with SBOM generation
  .bom.yaml
  .github/workflows/release.yaml
Labels: kind/feature, approved, size/M, cncf-cla: yes, sig/release, lgtm
