Repository kubernetes-sigs/release-utils, pull requests merged in 2025-09, with the labels that each got.

#147 go.mod: Bump k8s.io/utils to v0.0.0-20250820121507-0af2bda4dd1d
  go.mod
  go.sum
Labels: approved, area/dependency, kind/cleanup, cncf-cla: yes, sig/release, lgtm, size/XS

#149 Fix disable retries in http agent
  http/agent.go
Labels: kind/bug, approved, cncf-cla: yes, sig/release, lgtm, size/XS

#150 General Updates/housekeeping
  .github/dependabot.yml
  .github/workflows/release.yaml
  Dockerfile.dev
  dependencies.yaml
  helpers/common_test.go
  mage/cosign.go
  mage/golangci-lint.go
  version/command.go
Labels: approved, size/M, kind/cleanup, cncf-cla: yes, sig/release, lgtm
