Repository kubernetes-sigs/release-utils, pull requests merged in 2025-01, with the labels that each got.

#123 update golangci-lint to v1.63.4
  dependencies.yaml
  mage/golangci-lint.go
Labels: approved, kind/cleanup, cncf-cla: yes, sig/release, lgtm, size/XS

#125 Update golangci-lint config and fix reports
  .golangci.yml
  command/command.go
  command/command_test.go
  command/global.go
  editor/editor.go
  editor/editor_test.go
  editor/tty.go
  env/env.go
  hash/hash.go
  hash/hash_test.go
  http/agent.go
  http/example_multi_test.go
  http/http_test.go
  log/hooks.go
  log/log.go
  log/log_test.go
  log/step.go
  mage/cosign.go
  mage/golangci-lint.go
  mage/ko.go
  mage/version.go
  mage/version_test.go
  tar/tar.go
  tar/tar_test.go
  util/common.go
  util/common_test.go
  version/command.go
  version/command_test.go
  version/version.go
Labels: approved, size/L, kind/cleanup, cncf-cla: yes, sig/release, lgtm

#126 Use `go-retry` for HTTP retry
  go.mod
  go.sum
  http/agent.go
  http/agent_test.go
  http/http_test.go
Labels: kind/feature, approved, size/L, cncf-cla: yes, sig/release, lgtm
